import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import localFont from "next/font/local";
import "./globals.css";
import data from "@/data/data.json"
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Blogify 2.0",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const categories = [...new Set(data.map((d)=> d.category))];
  return (
    <html lang="en">
      <body
        className={`bg-white text-gray-900 ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <section class="py-10 border-t border-gray-200">
          <div class="container mx-auto px-4">
            <div class="flex flex-col lg:flex-row">
              {children}
              <Sidebar categories={categories}/>{" "}
            </div>
          </div>
        </section>
      </body>
    </html>
  );
}
